server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/billa1
    username: root
    password: Prashanth.009@
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

keycloak:
  realm: billasecurity
  auth-server-url: http://localhost:8180/auth
  resource: springbootkeyclock
  public-client: true
  bearer-only: true







